# set job name
job_name: debug

# path file data
input_content_path: ./data/coco_10
input_style_path: ./data/wikiart_10
content_file: coco_10.txt
style_file: wikiart_10.txt
output_path: ./output

# config data
height: 300
width: 400

# config model
seed: 0
n_flow: 15
n_block: 2
no_lu: False
affine: False
domain_code: 0
loss: tv_loss
vgg: ./vgg_model/vgg_normalised.pth
lr: 0.00005
lr_decay: 0.00005
max_iter: 10
lr_steps: [40000, 80000, 120000]
lr_mults: 0.5
last_iter: -1
batch_size: 1
bn_group: 4
bn_sync_stats: True

# config weights
mse_weight: 0
p_weight: 0.0
style_weight: 1
content_weight: 0.1

# other config
keep_ratio: 0.6
resume: False
debug: True
workers: 4
log_interval: 1
freq_save: 1

# config wandb
name: styleflow
id: null
