wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1670015021.219569
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      4: 3.9.13
      5: 0.13.5
      8:
      - 3
      - 5
affine:
  desc: null
  value: false
batch_size:
  desc: null
  value: 1
bn_group:
  desc: null
  value: 4
bn_sync_stats:
  desc: null
  value: true
config:
  desc: null
  value: D:\HK7\styleflow\configs\debug.yaml
content_file:
  desc: null
  value: ./data/coco_10.txt
content_weight:
  desc: null
  value: 0.1
debug:
  desc: null
  value: false
device:
  desc: null
  value: cpu
domain_code:
  desc: null
  value: 0
freq_save:
  desc: null
  value: 1
gpu_devices:
  desc: null
  value: []
height:
  desc: null
  value: 300
id:
  desc: null
  value: oe9l17s6
input_path:
  desc: null
  value: ./data
job_name:
  desc: null
  value: debug
keep_ratio:
  desc: null
  value: 0.6
last_iter:
  desc: null
  value: -1
log_interval:
  desc: null
  value: 1
loss:
  desc: null
  value: tv_loss
lr:
  desc: null
  value: 5.0e-05
lr_decay:
  desc: null
  value: 5.0e-05
lr_mults:
  desc: null
  value: 0.5
lr_steps:
  desc: null
  value:
  - 40000
  - 80000
  - 120000
max_iter:
  desc: null
  value: 5
mse_weight:
  desc: null
  value: 0
n_block:
  desc: null
  value: 2
n_flow:
  desc: null
  value: 15
name:
  desc: null
  value: styleflow
no_cuda:
  desc: null
  value: false
no_lu:
  desc: null
  value: false
output_path:
  desc: null
  value: ./output
p_weight:
  desc: null
  value: 0.0
resume:
  desc: null
  value: false
seed:
  desc: null
  value: 0
show_model:
  desc: null
  value: false
style_file:
  desc: null
  value: ./data/artist_10.txt
style_weight:
  desc: null
  value: 1
vgg:
  desc: null
  value: ./vgg_model/vgg_normalised.pth
wandb:
  desc: null
  value: true
width:
  desc: null
  value: 400
workers:
  desc: null
  value: 2
